"""
ui/session_header.py — Session header with patient form and timer
=================================================================================

This module implements the SessionHeaderWidget: the top bar of the interface that
collects session identification data BEFORE starting the camera.

Responsibilities:
    1. Identification form: patient name, evaluated hand, session number.
    2. Timer control: records the start time and displays elapsed time.
    3. Precondition validation: is_ready() ensures the session only starts when
       the minimum required data is filled in (patient name is mandatory).

Why collect this data here and not at the start of processing?
    The CSV generated by GoniometryCSVLogger and the PDF from session_report.py
    need the patient name, evaluated hand, and session number in their metadata.
    Collecting before starting ensures these fields are always available
    when the ProcessingWorker begins recording — no blank fields in the output file.

Usage flow in MainWindow:
    1. User fills the form.
    2. MainWindow calls is_ready() — monitors via QLineEdit.textChanged.
    3. When ready, the Start button is enabled.
    4. On Start click: MainWindow calls get_session_info() and start_timer().
    5. On End click: MainWindow calls stop_timer().
"""

from datetime import datetime, timedelta
from typing import Optional

from PyQt6.QtCore import Qt, QTimer, pyqtSignal
from PyQt6.QtWidgets import (
    QComboBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QSizePolicy,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)

from themes import (
    COLOR_ACCENT,
    COLOR_TEXT_PRIMARY,
    COLOR_TEXT_SECONDARY,
    LABEL_SECTION_TITLE_STYLE,
    SESSION_HEADER_STYLE,
)


class SessionHeaderWidget(QWidget):
    """
    Top bar of the goniometry interface with a patient form and session timer.

    Displayed permanently at the top of the MainWindow, regardless of the session
    state (IDLE, READY, RUNNING, STOPPED). Form fields are editable in IDLE/READY
    states and locked in RUNNING/STOPPED to prevent accidental changes during recording.

    Visual layout:
        ┌─────────────────────────────────────────────────────────────────────┐
        │ Patient: [___________________] Hand: [▾] Session: [▲1▼] │Start: 14:35│
        │                                                          │Elapsed: 00:12:48│
        └─────────────────────────────────────────────────────────────────────┘
    """

    hand_changed = pyqtSignal(str)

    def __init__(self, parent: Optional[QWidget] = None) -> None:
        """
        Initializes the header with all form fields and the session timer.

        The internal QTimer (_timer) is created here but NOT started —
        it is activated only when start_timer() is called by MainWindow.
        This ensures the timer does not start before the session begins.

        Parameters:
            parent: Qt parent widget (optional). Usually the MainWindow.
        """
        super().__init__(parent)

        # Apply differentiated visual style to separate the header from the rest.
        self.setStyleSheet(SESSION_HEADER_STYLE)

        # Size policy: expands horizontally, fixed height.
        self.setSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Fixed,
        )

        # Main horizontal layout — all fields are on the same row.
        main_layout = QHBoxLayout(self)
        main_layout.setContentsMargins(12, 8, 12, 8)
        main_layout.setSpacing(16)

        # === FIELD: Patient Name ===
        self._build_patient_field(main_layout)

        # === FIELD: Evaluated Hand ===
        self._build_hand_field(main_layout)

        # === FIELD: Session Number ===
        self._build_session_number_field(main_layout)

        # Vertical separator between form and timer.
        self._add_vertical_separator(main_layout)

        # === TIMER: Start Time + Elapsed Time ===
        self._build_timer_display(main_layout)

        # Push content to the left, keeping the timer aligned to the right.
        main_layout.addStretch()

        # === INTERNAL TIMER ===
        # QTimer that fires every 1000ms to update elapsed time.
        # interval=1000ms ensures second-level accuracy without CPU overhead.
        self._timer = QTimer(self)
        self._timer.setInterval(1000)
        self._timer.timeout.connect(self._tick)

        # Timestamp of when start_timer() was called.
        # None indicates the session has not yet started.
        self._start_time: Optional[datetime] = None

    # =========================================================================
    # FORM SECTION BUILDERS
    # =========================================================================

    def _build_patient_field(self, layout: QHBoxLayout) -> None:
        """
        Creates the patient name field with label and QLineEdit.

        The name is the only REQUIRED field — is_ready() returns False
        while this field is empty or contains only whitespace.

        Parameters:
            layout: Parent layout where the widget group will be added.
        """
        # Vertical container: label on top, text field below.
        container = QVBoxLayout()
        container.setSpacing(2)
        container.setContentsMargins(0, 0, 0, 0)

        lbl = QLabel("Patient")
        lbl.setStyleSheet(LABEL_SECTION_TITLE_STYLE)

        # QLineEdit with placeholder to guide the user.
        # maxLength=100: prevents excessively long names that could
        # cause issues in the generated CSV filename.
        self._input_patient = QLineEdit()
        self._input_patient.setPlaceholderText("Full patient name...")
        self._input_patient.setMaxLength(100)
        self._input_patient.setMinimumWidth(220)
        self._input_patient.setStyleSheet(
            f"QLineEdit {{ color: {COLOR_TEXT_PRIMARY}; padding: 4px 8px; "
            f"border: 1px solid #334155; border-radius: 5px; "
            f"background: #16213e; font-size: 13px; }}"
            f"QLineEdit:focus {{ border-color: {COLOR_ACCENT}; }}"
        )

        container.addWidget(lbl)
        container.addWidget(self._input_patient)
        layout.addLayout(container)

    def _build_hand_field(self, layout: QHBoxLayout) -> None:
        """
        Creates the evaluated hand selector with QComboBox.

        "Right" and "Left" correspond to the 'side' parameter of
        generate_pdf_report() and the is_right_hand parameter of DigitalGoniometer.

        Parameters:
            layout: Parent layout where the widget group will be added.
        """
        container = QVBoxLayout()
        container.setSpacing(2)
        container.setContentsMargins(0, 0, 0, 0)

        lbl = QLabel("Evaluated Hand")
        lbl.setStyleSheet(LABEL_SECTION_TITLE_STYLE)

        self._combo_hand = QComboBox()
        self._combo_hand.addItems(["Right", "Left"])
        self._combo_hand.setMinimumWidth(100)
        self._combo_hand.currentTextChanged.connect(self.hand_changed.emit)
        self._combo_hand.setStyleSheet(
            f"QComboBox {{ color: {COLOR_TEXT_PRIMARY}; padding: 4px 8px; "
            f"border: 1px solid #334155; border-radius: 5px; "
            f"background: #16213e; font-size: 13px; }}"
            f"QComboBox:focus {{ border-color: {COLOR_ACCENT}; }}"
            f"QComboBox QAbstractItemView {{ background: #16213e; "
            f"color: {COLOR_TEXT_PRIMARY}; selection-background-color: {COLOR_ACCENT}; }}"
        )

        container.addWidget(lbl)
        container.addWidget(self._combo_hand)
        layout.addLayout(container)

    def _build_session_number_field(self, layout: QHBoxLayout) -> None:
        """
        Creates the session number field with QSpinBox.

        The session number chronologically identifies evaluations of the same
        patient. Defaults to 1; the clinician increments it manually
        for each new session with the same patient.

        Parameters:
            layout: Parent layout where the widget group will be added.
        """
        container = QVBoxLayout()
        container.setSpacing(2)
        container.setContentsMargins(0, 0, 0, 0)

        lbl = QLabel("Session #")
        lbl.setStyleSheet(LABEL_SECTION_TITLE_STYLE)

        # Minimum 1: session 0 or negative makes no sense.
        # Maximum 999: reasonable for any real clinical history.
        self._spin_session = QSpinBox()
        self._spin_session.setMinimum(1)
        self._spin_session.setMaximum(999)
        self._spin_session.setValue(1)
        self._spin_session.setMinimumWidth(70)
        self._spin_session.setStyleSheet(
            f"QSpinBox {{ color: {COLOR_TEXT_PRIMARY}; padding: 4px 8px; "
            f"border: 1px solid #334155; border-radius: 5px; "
            f"background: #16213e; font-size: 13px; }}"
            f"QSpinBox:focus {{ border-color: {COLOR_ACCENT}; }}"
        )

        container.addWidget(lbl)
        container.addWidget(self._spin_session)
        layout.addLayout(container)

    def _build_timer_display(self, layout: QHBoxLayout) -> None:
        """
        Creates the timer display with start time and elapsed time.

        Both labels are stacked vertically, right-aligned.
        The start time is populated by start_timer().
        The elapsed time is updated by _tick() every second.

        Parameters:
            layout: Parent layout where the display will be added.
        """
        container = QVBoxLayout()
        container.setSpacing(4)
        container.setContentsMargins(0, 0, 0, 0)
        container.setAlignment(Qt.AlignmentFlag.AlignRight)

        # --- "Start:" row ---
        row_start = QHBoxLayout()
        row_start.setSpacing(6)

        lbl_start_title = QLabel("Start:")
        lbl_start_title.setStyleSheet(LABEL_SECTION_TITLE_STYLE)

        # Populated by start_timer() with the actual start time.
        self._lbl_start_time = QLabel("—")
        self._lbl_start_time.setStyleSheet(
            f"QLabel {{ color: {COLOR_TEXT_PRIMARY}; font-size: 14px; "
            f"font-weight: bold; font-family: 'Consolas', monospace; }}"
        )

        row_start.addWidget(lbl_start_title)
        row_start.addWidget(self._lbl_start_time)

        # --- "Elapsed:" row ---
        row_elapsed = QHBoxLayout()
        row_elapsed.setSpacing(6)

        lbl_elapsed_title = QLabel("Elapsed:")
        lbl_elapsed_title.setStyleSheet(LABEL_SECTION_TITLE_STYLE)

        # Updated every second by the QTimer via _tick().
        # Monospaced font: prevents layout "jumping" when digits change
        # (variable-width digits in proportional fonts cause text shifts).
        self._lbl_elapsed = QLabel("00:00:00")
        self._lbl_elapsed.setStyleSheet(
            f"QLabel {{ color: {COLOR_ACCENT}; font-size: 18px; "
            f"font-weight: bold; font-family: 'Consolas', monospace; }}"
        )

        row_elapsed.addWidget(lbl_elapsed_title)
        row_elapsed.addWidget(self._lbl_elapsed)

        container.addLayout(row_start)
        container.addLayout(row_elapsed)
        layout.addLayout(container)

    def _add_vertical_separator(self, layout: QHBoxLayout) -> None:
        """
        Adds a vertical separator between the form and the timer.

        QFrame with frameShape=VLine creates a thin vertical bar used as
        a visual divider to logically separate the two header sections:
        identification data (left) and timer (right).

        Parameters:
            layout: Parent layout where the separator will be inserted.
        """
        separator = QFrame()
        separator.setFrameShape(QFrame.Shape.VLine)
        separator.setFrameShadow(QFrame.Shadow.Sunken)
        separator.setStyleSheet("color: #334155;")
        separator.setFixedWidth(2)
        layout.addWidget(separator)

    # =========================================================================
    # PUBLIC INTERFACE — used by MainWindow
    # =========================================================================

    def is_ready(self) -> bool:
        """
        Checks whether the minimum conditions to start a session are met.

        Required condition: patient name filled in (not empty, not only whitespace).
        The evaluated hand and session number always have valid default values,
        so they do not need separate validation.

        Used by MainWindow to enable/disable the "Start Session" button
        in response to QLineEdit.textChanged events.

        Returns:
            bool: True if the patient name is filled in, False otherwise.
        """
        # strip() removes leading/trailing whitespace — prevents "   " (only spaces)
        # from being accepted as a valid name, which would create CSV files without
        # real identification.
        return bool(self._input_patient.text().strip())

    def get_session_info(self) -> dict:
        """
        Returns the form data as a dictionary for use in the pipeline.

        Should be called by MainWindow when starting the session, AFTER is_ready()
        returns True. The returned data feeds:
        - ProcessingWorker.start_session(csv_path): name + session for the filename.
        - generate_pdf_report(): patient_name and side for the PDF report.
        - GoniometryCSVLogger: metadata in the CSV header.

        Returns:
            dict with keys:
                patient_name (str): Full patient name without extra whitespace.
                hand (str): "Right" or "Left" — as selected in the ComboBox.
                session_number (int): Session number (1–999).
                start_time (datetime | None): Session start time,
                    or None if start_timer() has not yet been called.
        """
        return {
            # strip() ensures the name contains no unnecessary whitespace
            # that could appear in the CSV filename or the PDF.
            "patient_name": self._input_patient.text().strip(),
            "hand": self._combo_hand.currentText(),
            "session_number": self._spin_session.value(),
            "start_time": self._start_time,
        }

    def start_timer(self) -> None:
        """
        Records the session start time and activates the timer.

        Called by MainWindow immediately after starting the workers.
        Does three things:
        1. Records datetime.now() as the timer's zero point.
        2. Displays the start time in the corresponding label.
        3. Starts the QTimer that will call _tick() every 1000ms.

        Why datetime.now() and not time.monotonic()?
            datetime.now() provides the real clock time (to display "14:35:12")
            AND allows computing elapsed time by subtracting datetimes.
            time.monotonic() would be more precise for intervals, but does not
            provide the time of day — two separate variables would be needed.
        """
        # Record the exact start moment with microsecond precision.
        # Microseconds are truncated in display but kept internally so that
        # _tick() computes elapsed time with second-level accuracy.
        self._start_time = datetime.now()

        # Display the start time formatted as HH:MM:SS.
        self._lbl_start_time.setText(
            self._start_time.strftime("%H:%M:%S")
        )

        # Reset the elapsed time display to ensure it shows 00:00:00
        # before the first _tick() is called (after ~1 second).
        self._lbl_elapsed.setText("00:00:00")

        # Start the timer — from now on _tick() will be called every second.
        # If the timer is already active (duplicate call), start() restarts it.
        self._timer.start()

    def stop_timer(self) -> None:
        """
        Stops the timer and freezes the elapsed time display.

        Called by MainWindow when ending the session. The display freezes on
        the last displayed value, allowing the clinician to read the total
        session duration even after processing stops.

        This method does not clear the start time or elapsed time —
        those remain visible for reference until a new session begins.
        """
        # Stop the QTimer — _tick() will no longer be called.
        if self._timer.isActive():
            self._timer.stop()

    def reset(self) -> None:
        """
        Resets the form and timer to their initial state.

        Called by MainWindow when starting a new session after a previous one
        has ended, or on a future "New Session" button click.
        Does not increment the session number — that should be done manually
        by the clinician to maintain control over session numbering.

        Note: does not clear the patient name — the clinician may want to
        start another session for the same patient without retyping.
        """
        # Stop the timer if active.
        self.stop_timer()

        # Clear time references.
        self._start_time = None

        # Reset displays to the "no data" state.
        self._lbl_start_time.setText("—")
        self._lbl_elapsed.setText("00:00:00")

    def set_fields_enabled(self, enabled: bool) -> None:
        """
        Enables or disables the form input fields.

        Called by MainWindow when transitioning between states:
        - RUNNING: disables fields (do not change data during recording).
        - STOPPED/IDLE: enables fields (allows editing for the next session).

        Parameters:
            enabled: True to enable editing, False to lock.
        """
        self._input_patient.setEnabled(enabled)
        self._combo_hand.setEnabled(enabled)
        self._spin_session.setEnabled(enabled)

    # =========================================================================
    # INTERNAL TIMER LOGIC
    # =========================================================================

    def _tick(self) -> None:
        """
        Computes and displays elapsed time since the session started.

        Called by the internal QTimer every 1000ms (1 second).
        Should not be called directly — it is connected to the timer in start_timer().

        Why compute elapsed on each tick instead of incrementing a counter?
            Incrementing an integer counter (seconds += 1) accumulates error: if any
            tick takes longer than 1 second (e.g., overloaded CPU), the counter would
            fall behind the real clock. Computing elapsed as (now - start) always
            gives the correct real time regardless of QTimer interval variations.
        """
        if self._start_time is None:
            # Defensive guard: timer running without a defined start time.
            return

        # Compute the real elapsed interval since the session start.
        elapsed: timedelta = datetime.now() - self._start_time

        # Extract hours, minutes, and seconds from the timedelta.
        # total_seconds() returns the total as a float.
        # We divide and apply modulo to get H:M:S independently.
        total_seconds: int = int(elapsed.total_seconds())

        # Hours, minutes, and remaining seconds.
        hours: int = total_seconds // 3600
        minutes: int = (total_seconds % 3600) // 60
        seconds: int = total_seconds % 60

        # Format as "HH:MM:SS" with leading zeros.
        # :02d = integer with minimum 2 digits, zero-padded.
        elapsed_str: str = f"{hours:02d}:{minutes:02d}:{seconds:02d}"

        self._lbl_elapsed.setText(elapsed_str)
